In [3]:
import sys,os
USER = os.environ['USERPROFILE']
sys.path.insert(1,f'{USER}\\PycharmProjects\\my_utility')

from utility_code.my_utility import *
from utility_code.python_lib_essential import *



In [12]:

print('With the same seed')
np.random.seed(31415) 
print(np.random.random((2,2)))
# np.random.seed(31415) # reset the random seed back to 31415
print(np.random.random((2,2)))
np.random.seed(31415) 
print(np.random.random((2,2)))
# np.random.seed(31415) # reset the random seed back to 31415
print(np.random.random((2,2)))

With the same seed
[[0.64581861 0.67517417]
 [0.97070399 0.88480436]]
[[0.90906584 0.82359297]
 [0.48670972 0.62099358]]
[[0.64581861 0.67517417]
 [0.97070399 0.88480436]]
[[0.90906584 0.82359297]
 [0.48670972 0.62099358]]


In [13]:
import numpy as np
from sklearn.model_selection import StratifiedKFold
X = np.array([[1, 2], [3, 4], [3, 4], [3, 4], [1, 2], [3, 4]])
y = np.array([0, 0, 0,0,1, 1])
skf = StratifiedKFold(n_splits=4)
skf.get_n_splits(X, y)

print(skf)  

for train_index, test_index in skf.split(X, y):
   print("TRAIN:", train_index, "TEST:", test_index)
   X_train, X_test = X[train_index], X[test_index]
   y_train, y_test = y[train_index], y[test_index]

StratifiedKFold(n_splits=4, random_state=None, shuffle=False)


C:\Users\awannaphasch2016\AppData\Local\Continuum\anaconda3\envs\pytorch_python3.7\lib\site-packages\sklearn\model_selection\_split.py:657: Warning: The least populated class in y has only 2 members, which is too few. The minimum number of members in any class cannot be less than n_splits=4.
  % (min_groups, self.n_splits)), Warning)


TRAIN: [1 2 3 5] TEST: [0 4]
TRAIN: [0 2 3 4] TEST: [1 5]
TRAIN: [0 1 3 4 5] TEST: [2]
TRAIN: [0 1 2 4 5] TEST: [3]


In [22]:
x = True
y = 'a'
if x and y is not None: 
    print("yes")
else:
    print("No")

yes


In [23]:
if x and y is not None: 
    print("yes")
if not x or y is None: 
    print("No")

yes


In [25]:
import torch

In [30]:
x = torch.rand((3,2))
x

tensor([[0.7349, 0.3619],
        [0.1195, 0.7841],
        [0.0391, 0.3329]])

In [31]:
x.size(1)

2