In [4]:
import numpy as np
x = np.arange(6).reshape(2,-1)
np.where(x>2)

(array([1, 1, 1], dtype=int64), array([0, 1, 2], dtype=int64))

In [7]:
x = np.arange(10).reshape(5,-1)
x.nonzero()

(array([0, 1, 1, 2, 2, 3, 3, 4, 4], dtype=int64),
 array([1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int64))

In [8]:
x[x>2]

array([3, 4, 5, 6, 7, 8, 9])

In [9]:
x.t

AttributeError: 'numpy.ndarray' object has no attribute 't'

In [10]:
x.T

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [17]:
from sklearn import datasets, linear_model, svm
from sklearn.model_selection import cross_val_predict
diabetes = datasets.load_diabetes()
X = diabetes.data[:150]
y = diabetes.target[:150]
# clf = linear_model.Lasso()
clf = svm.SVC(gamma='scale', decision_function_shape='ovr', probability=True)
y_pred = cross_val_predict(clf, X, y, cv=3 ,method='predict_proba')


C:\Users\awannaphasch2016\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:652: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)
C:\Users\awannaphasch2016\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:865: RuntimeWarning: Number of classes in training fold (34) does not match total number of classes (107). Results may not be appropriate for your use case. To fix this, use a cross-validation technique resulting in properly stratified folds
  RuntimeWarning)


In [24]:
y_pred[]


SyntaxError: invalid syntax (<ipython-input-24-9a191c5646f6>, line 1)

In [26]:
# x = np.array([[1,2,1],[1,1,1],[2,2,1]])
x = np.array([1,2,1])
np.bincount(x)

array([0, 2, 1], dtype=int64)

In [37]:
def count(x, return_counts):
    return np.unique(x)
x = np.array([[1,2,4],[4,4,4]])
np.apply_along_axis(count,1,x,True)

array([[1, 2, 4],
       [4, 4, 4]])

In [38]:
 b = np.array([[8,1,7], [4,3,9], [5,2,6]])

In [43]:
np.unique(x, axis=0, return_counts=True)

(array([[1, 2, 4],
        [4, 4, 4]]), array([1, 1], dtype=int64))

In [44]:
x

array([[1, 2, 4],
       [4, 4, 4]])

In [49]:
from scipy.stats import mode
x = [1,2,2,2,1,1,1,1,1]
mode(x)[0][0]

1

In [51]:
x = np.array([[1,2,4],[4,4,4]])

In [54]:
tmp=np.apply_along_axis(mode,1, x)

In [57]:
[i[0][0] for i in tmp.tolist()]

[1, 4]

In [58]:
x = (2)

In [63]:
x = ({'y':5},)

In [64]:
x[0]['y']

5

In [96]:
import numpy as np
from scipy.stats import mode
x = np.array([[1,1,1],[2,2,2],[1,2,2],[3,2,1]])
np.apply_along_axis(mode, 0, x)[0][0]

array([1, 2, 1])

In [92]:
np.unique(x, axis=)


array([[1, 1, 1],
       [2, 2, 2],
       [1, 2, 3],
       [3, 2, 1]])

In [98]:
np.where(x == 1)

(array([0, 0, 0, 2, 3], dtype=int64), array([0, 1, 2, 0, 2], dtype=int64))

In [99]:
x

array([[1, 1, 1],
       [2, 2, 2],
       [1, 2, 2],
       [3, 2, 1]])

In [105]:
x = np.array([1,1,1,1,2,2])
y = np.array([2,2,1,1,2,3])
# np.in1d(y,x)
np.in1d(x,y)

array([ True,  True,  True,  True,  True,  True])

In [108]:
np.hstack((x,[1,1]))

array([1, 1, 1, 1, 2, 2, 1, 1])

In [109]:
import numpy as np
from sklearn.metrics import precision_recall_fscore_support
y_true = np.array(['cat', 'dog', 'pig', 'cat', 'dog', 'pig'])
y_pred = np.array(['cat', 'pig', 'dog', 'cat', 'cat', 'dog'])

In [110]:
precision_recall_fscore_support(y_true, y_pred, average=None,
labels=['pig', 'dog', 'cat'])

(array([0.        , 0.        , 0.66666667]),
 array([0., 0., 1.]),
 array([0. , 0. , 0.8]),
 array([2, 2, 2], dtype=int64))

In [111]:
precision_recall_fscore_support(y_true, y_pred, average=None,
labels=[ 'dog', 'cat','pig'])

(array([0.        , 0.66666667, 0.        ]),
 array([0., 1., 0.]),
 array([0. , 0.8, 0. ]),
 array([2, 2, 2], dtype=int64))